### ISSUE TITLE
New release breaks encrypt with only one argument (1.0.0 had only one argument)

### ISSUE THREAD

**Issue by colloqi** [http-auth/apache-md5#2]
node_modules/apache-md5/lib/apache-md5.js:61 if (salt.split('$')[1] === '1') { ^ TypeError: Cannot call method 'split' of undefined at MD5.encrypt (/home/pi/piSignagePro/node_modules/apache-md5/lib/apache-md5.js:61:18) 

Thanks

**Comment by gevorg** [comment]
Thank you for reporting issue! Must be fixed with latest version. Gevorg
