### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by FStefanni** [http-auth/apache-md5#7]
Hi,

working with typescript I have written a simple file definition for this library, with the following content:
```typescript

declare function aprMd5(password: string, salt?: string): string;

export default aprMd5;
```

I believe it could be nice to add it it in the package, for other users.
It suffices to add an `apache-md5.d.ts` file inside the `src` directory.

Best regards.

**Comment by gevorg** [comment]
@FStefanni thanks, please open PR and I will publish new version.

**Comment by FStefanni** [comment]
PR done (#11)
